name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3.9.1
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      # Optional jika kamu punya test script
      - name: Run tests
        run: npm test

      # Optional jika kamu punya build script
      - name: Build
        run: npm run build
