name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Start server in background
        run: |
          nohup node server.js &
          sleep 5

      # Contoh: Run tests yang butuh akses ke server
      - name: Run API tests
        run: |
          curl http://localhost:3000/api/jobs || exit 1
          # atau jalankan npm test yang butuh server ini

      # Optional build step
      - name: Build
        run: npm run build
